#!/bin/bash
set -euo pipefail

pc_file=build/payload_constants.mk

build_demo() {
    make -j
    cd app
    idf.py build
    riscv32-esp-elf-objdump -d build/emoji.elf  > build/emoji.diss
    PUTS=$(cat build/emoji.diss | grep "<puts>:" | cut -d' ' -f1)
    WIN=$(cat build/emoji.diss | grep "<debug_display_private_key>:" | cut -d' ' -f1)
    cd -
    printf "PAYLOAD_PUTS:=0x${PUTS}\nPAYLOAD_DUMP_PRIVATE_KEY:=0x${WIN}\n" > "${pc_file}.tmp"
    cmp -s "${pc_file}" "${pc_file}.tmp"
}

build_demo || (mv "${pc_file}.tmp" "${pc_file}" && build_demo)
cd app
./w
